#!/bin/bash

CONF_FILE='/etc/pica/pica.conf'

exit_error() {
  echo "${*}" >&2
  exit 1
}

continue_error() {
  echo "${*}" >&2
  continue
}

save_report() {
  echo "REPORT_STATUS=${2}" > "${1}~" || exit_error "Write report file ${1}~ failed"
  mv "${1}~" "${1}" || exit_error "Write cache file ${1} failed"
}

# запись кэш файла
# 1 - PATHFILE
# 2 - PA_VERSION
# 3 - RESULT
# 4 - PA_COMMENT_OK
# 5 - PA_COMMENT_FAIL
save_cache() {
  echo "CACHE_VERSION=\"${2}\"" > "${1}~" || exit_error "Write cache file ${1}~ failed"
  echo "CACHE_STATUS=\"${3}\"" >> "${1}~" || exit_error "Write cache file ${1}~ failed"
  [ "${RESULT}" = 'OK' ] && COMMENT="${PA_COMMENT_OK}" || COMMENT="${PA_COMMENT_FAIL}"
  echo "CACHE_COMMENT=\"${COMMENT}\"" >> "${1}~" || exit_error "Write cache file ${1}~ failed"
  mv "${1}~" "${1}" || exit_error "Write cache file ${1} failed"
}

set_param() {
  FILENAME="${1}"
  shift
  while read LINE; do
    if [ "$(echo ${@} ${LINE%%=*} | tr ' ' '\n' | sort | uniq -d)" = "${LINE%%=*}" ]; then
      eval "${LINE%%=*}=${LINE#*=}"
    else
      echo "Error line: ${LINE}"  >&2
      return 1
    fi
  done < "${FILENAME}"
}

# проверка наличия conf файла
[ -f "${CONF_FILE}" ] || exit_error "Conf file ${CONF_FILE} does not exist"

# проверка права чтения conf файла
[ -r "${CONF_FILE}" ] || exit_error "Can not read conf file ${CONF_FILE}"

# загружаем из конфигурационного файла указанные опции
set_param "${CONF_FILE}" PICA_TAGS PICA_TEST_DIR PICA_TEST_CACHE_DIR PICA_REPORT_DIR PICA_EXCEPTIONS \
  || exit_error "Error loading config file ${CONF_FILE}"

[ -z "${PICA_TAGS}" ] && exit_error "${PICA_TAGS}\'s not exist in ${CONF_FILE}"
[ -z "${PICA_TEST_DIR}" ] && exit_error "${PICA_TEST_DIR}\'s not exist in ${CONF_FILE}"
[ -z "${PICA_TEST_CACHE_DIR}" ] && exit_error "${PICA_TEST_CACHE_DIR}\'s not exist in ${CONF_FILE}"
[ -z "${PICA_REPORT_DIR}" ] && exit_error "${PICA_REPORT_DIR}\'s not exist in ${CONF_FILE}"
[ -z "${PICA_EXCEPTIONS}" ] && exit_error "${PICA_EXCEPTIONS}\'s not exist in ${CONF_FILE}"

# проверка наличия папки с тестами и возможности чтения
[ -d "${PICA_TEST_DIR}" -a -r "${PICA_TEST_DIR}" -a -x "${PICA_TEST_DIR}" ] \
  || exit_error "Test's directory ${PICA_TEST_DIR} not found or unreadable"

# проверка непустоты папка с тестами
[ -z "$(ls ${PICA_TEST_DIR})" ] && exit_error "Test's folder is empty"

# проверка наличия папки с кэшем и возможности записи
[ -d "${PICA_TEST_CACHE_DIR}" -a -w "${PICA_TEST_CACHE_DIR}" -a -r "${PICA_TEST_CACHE_DIR}" -a -x "${PICA_TEST_CACHE_DIR}" ] \
  || exit_error "Cache directory ${PICA_TEST_CACHE_DIR} not found or has wrong permissions"

REPORT_WARNING=0
REPORT_CRITICAL=0

# переборка всех тест файлов
for TEST_FILE in "${PICA_TEST_DIR}"/*.pa; do

  # проверка тест файла на читаемость
  if ! [ -r "${TEST_FILE}" ]; then
    echo "Test file ${TEST_FILE} is unreadable" >&2
    continue
  fi

  # очищение среды для нового теста
  unset ${PA_VERSION}
  unset ${PA_TAG}
  unset ${PA_COMMAND}
  unset ${PA_COMMENT_OK}
  unset ${PA_COMMENT_FAIL}
  unset ${PA_EXPIRE}
  unset ${PA_SEVERITY}

  source "${TEST_FILE}" || continue_error "can not load ${TEST_FILE}" 
  [ -z "${PA_VERSION}" ] && continue_error "${PA_VERSION} is not exist in ${TEST_FLE}"
  [ -z "${PA_TAG}" ] && continue_error "${PA_TAG} is not exist in ${TEST_FLE}"
  [ -z "${PA_COMMAND}" ] && continue_error "${PA_COMMAND} is not exist in ${TEST_FLE}"
  [ -z "${PA_COMMENT_OK}" ] && continue_error "${PA_COMMENT_OK} is not exist in ${TEST_FLE}"
  [ -z "${PA_COMMENT_FAIL}" ] && continue_error "${PA_COMMENT_FAIL} is not exist in ${TEST_FLE}"
  [ -z "${PA_EXPIRE}" ] && continue_error "${PA_EXPIRE} is not exist in ${TEST_FLE}"
  [ -z "${PA_SEVERITY}" ] && continue_error "${PA_SEVERITY} is not exist in ${TEST_FLE}"

  # отсечение тестов с неудовлетворяющим тегом
  COMMON_TAG=$(echo ${PICA_TAGS[@]} ${PA_TAG[@]} | tr ' ' '\n' | sort | uniq -d) 
  [ -z "${COMMON_TAG}" ] && continue

  # исключение тестов по имени в глобальном конфиге
  [ -n "$(echo ${PICA_EXCEPTIONS[@]} ${TEST_FILE##*/} | tr ' ' '\n' | sort | uniq -d)" ] && continue

  echo -n "${TEST_FILE##*/}... " >&2 

  # фильтрация тестов по EXPIRED
  LIFETIME_OF_CACHE=$[$(date +'%s')-$(stat -c '%Z' ${PICA_TEST_CACHE_DIR}/${TEST_FILE##*/}.cache)]
  # проверка кэша по EXPIRE
  if [ "${LIFETIME_OF_CACHE}" -lt "${PA_EXPIRE}" ]; then
    echo 'cached' >&2
    continue
  fi



  if ${PA_COMMAND} >/dev/null 2>/dev/null; then
    RESULT='OK'
  else
    RESULT="${PA_SEVERITY}"
  fi
  #echo "${RESULT}" | tee "${PICA_TEST_CACHE_DIR}/${TEST_FILE##*/}.cache" >&2
  echo "${RESULT}" >&2

  # создание статуса для отчета
  if [ "${RESULT}" = "CRITICAL" ]; then
    let "REPORT_CRITICAL = REPORT_CRITICAL + 1"
  elif [ "${RESULT}" = "WARNING" ]; then
    let "REPORT_WARNING = REPORT_WARNING + 1"
  fi

  save_cache "${PICA_TEST_CACHE_DIR}/${TEST_FILE##*/}.cache" "${PA_VERSION}" "${RESULT}" "${PA_COMMENT_OK}" "${PA_COMMENT_FAIL}"
  
  [ "${RESULT}" = 'OK' ] && COMMENT="${PA_COMMENT_OK}" || COMMENT="${PA_COMMENT_FAIL}"
  TEST_COMMENTS="${TEST_COMMENTS}\n ${TEST_FILE##*/} : ${COMMENT} "
done


if [ ${REPORT_WARNING} = 0 -a ${REPORT_CRITICAL} = 0 ]; then
  REPORT_STATUS="OK"
elif [ ${REPORT_WARNING} != 0 -a ${REPORT_CRITICAL} = 0 ]; then
  REPORT_STATUS="WARNING"
elif [ ${REPORT_CRITICAL} != 0 ]; then
  REPORT_STATUS="CRITICAL"
fi

# Запись статуса в отчет

echo "REPORT_STATUS=${REPORT_STATUS}" > "${PICA_REPORT_DIR}/report~" || exit_error "Write report file ${PICA_REPORT_DIR}/report~ failed"

echo -e "${TEST_COMMENTS}" >> "${PICA_REPORT_DIR}/report~" || exit_error "Write report file ${PICA_REPORT_DIR}/report~ failed"


mv "${PICA_REPORT_DIR}/report~" "${PICA_REPORT_DIR}/report" || exit_error "Write cache file ${1} failed"
